### ISSUE TITLE
rake db:migrate error

### ISSUE THREAD

**Issue by caiqinghua** [boriscy/bonsaiERP#4]
When rake db:migrate on mac os x, errors is below.

20131224080216_add_hstore.rb

bonsaiERP git:(master) ✗ rake db:migrate
== 20131224080216 AddHstore: migrating ========================================
-- execute("CREATE EXTENSION IF NOT EXISTS hstore SCHEMA public")
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::InsufficientPrivilege: ERROR:  permission denied to create extension "hstore"
HINT:  Must be superuser to create this extension.
: CREATE EXTENSION IF NOT EXISTS hstore SCHEMA public/Users/cai/.rvm/gems/ruby-2.2.2@rails-4.2/gems/activerecord-4.2.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `async_exec'

**Comment by boriscy** [comment]
As you can see the error comes from not having enough privileges to create the extension you might need to give a higher privilege to the user in your config/database.yml, please I have moved bonsaiERP to https://github.com/bonsaiERP/bonsaiERP
